### ISSUE TITLE
EOFError: Ran out of input

### ISSUE THREAD

**Issue by Barnonewdm** [PeterWang512/FALdetector#13]
`python global_classifier.py --input_path ./examples/modified.jpg --model_path ./weights/global.pth --gpu_id 1`

`Traceback (most recent call last):
  File "global_classifier.py", line 64, in <module>
    model = load_classifier(args.model_path, args.gpu_id)
  File "global_classifier.py", line 19, in load_classifier
    state_dict = torch.load(model_path, map_location='cpu')
  File "/data/weidongming/Tools/miniconda3/envs/torch/lib/python3.6/site-packages/torch/serialization.py", line 387, in load
    return _load(f, map_location, pickle_module, **pickle_load_args)
  File "/data/weidongming/Tools/miniconda3/envs/torch/lib/python3.6/site-packages/torch/serialization.py", line 564, in _load
    magic_number = pickle_module.load(f, **pickle_load_args)
EOFError: Ran out of input
`
Could help me?

**Comment by PeterWang512** [comment]
It might be that your `weights/global.pth` is not downloaded properly. Can you try downloading the model weights again and see if it works?

**Comment by PeterWang512** [comment]
Also, you can try to download the weights manually. Here are the links:
global.pth: https://www.dropbox.com/s/rb8zpvrbxbbutxc/global.pth?dl=0
local.pth: https://www.dropbox.com/s/pby9dhpr6cqziyl/local.pth?dl=0
