### ISSUE TITLE
ValueError: cannot set WRITEABLE flag to True of this array

### ISSUE THREAD

**Issue by Piiiiiii** [PeterWang512/FALdetector#7]
After https://github.com/PeterWang512/FALdetector/issues/4, another error appears.

Traceback (most recent call last):
  File "global_classifier.py", line 65, in <module>
    prob = classify_fake(model, args.input_path, args.no_crop)
  File "global_classifier.py", line 36, in classify_fake
    faces = face_detection(img_path, verbose=False)
  File "F:\Study\Fun\AntiPs\FALdetector-master\utils\tools.py", line 108, in face_detection
    im.setflags(write=True)
ValueError: cannot set WRITEABLE flag to True of this array

**Comment by fkmajiji** [comment]
I have the same problem. How do you solve this problem?
